spring: 
  application:
    name: LEAVE-SERVICE	

  datasource: 
    url: jdbc:postgresql://localhost:5432/leaveManagement
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9020
