spring:
  application:
    name: Question-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/quizedb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9030

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka
    

    