spring:
  application:
    name: CustomerOrderSpringMVCProject

  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customerOrder
    username: postgres
    password: postgres

  sql: 
    init:
      mode: always

  jpa:
     hibernate:
       ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
